// validate input 
$(function() {
    $("form[name='add-product']").validate({
      rules: {
        tensanpham: "required",
        soluongton: "required",
        giasanpham: "required",
        manhacungung: "required",
        madonhang: "required",
        mamonan: "required",
        ngaynhap: "required",
        doanhthungay: "required",
        doanhthuthang: "required",
        hoten: "required",
        diachi: "required",
        email: "required",
        mataikhoan: "required",
        ngaylap: "required",
        ngayhethan: "required",
        nguoidaidien: "required",
        stk: "required",
        nganhang: "required",
        tenmonan: "required",
        mieutamonan:"required",
        giamonan:"required",
        machinhanh: "required",
        tenchinhanh: "required",
        diachichinhanh:"required",
        giomocuachinhanh:"required",
        giodongcuachinhanh:"required",
        tenquan: "required",
        donhangdukien: "required",
        loaiamthuc: "required",
        sdt: "required"
      },
      messages: {
        tensanpham: "Hãy nhập tên sản phẩm",
        soluongton: "Hãy nhập số lượng tồn",
        giasanpham: "Hãy nhập giá sản phẩm",
        manhacungung: "Hãy nhập mã nhà cung ứng",
        madonhang: "Hãy nhập mã đơn hàng",
        mamonan: "Hãy nhập mã sản phẩm",
        ngaynhap: "Hãy nhập ngày nhập",
        doanhthungay: "Hãy nhập ngày",
        doanhthuthang: "Hãy nhập tháng",
        hoten: "Hãy nhập họ tên",
        diachi: "Hãy nhập địa chỉ",
        email: "Hãy nhập email",
        mataikhoan: "Hãy nhập mã tài khoản",
        ngaylap: "Hãy nhập ngày lập",
        ngayhethan: "Hãy nhập ngày hết hạn",
        nguoidaidien: "Hãy nhập người đại diện",
        stk: "Hãy nhập STK",
        nganhang: "Hãy nhập ngân hàng",
        tenmonan: "Hãy nhập tên món ăn",
        mieutamonan:"Hãy nhập miêu tả món ăn",
        giamonan:"Hãy nhập giá",
        machinhanh: "Hãy nhập mã chi nhánh",
        tenchinhanh: "Hãy nhập tên chi nhánh",
        diachichinhanh:"Hãy nhập địa chỉ chi nhánh",
        giomocuachinhanh:"Hãy nhập giờ mở cửa chi nhánh",
        giodongcuachinhanh:"Hãy nhập giờ đóng cửa chi nhánh",
        tenquan: "Hãy nhập tên quán",
        donhangdukien: "Hãy nhập đơn hàng dự kiến",
        loaiamthuc: "Hãy nhập loại ẩm thực",
        sdt: "Hãy nhập số điện thoại"
      },
      submitHandler: function(form) {
        form.submit();
      }
    });
  });

